config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
 validates :title, presence: true, length: {minimum:3,maximum:50} #makes title compulsory
 validates :description, presence: true, length: {minimum:10,maximum:300}
end    

#getters & setters are provided by
#model allows adding validation/ constraints at model layer

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:edit, :update, :show, :destroy]
    def index #to list articles route is localhost:3000/article
      @articles=Article.all
    end
    
    def new
     @article=Article.new
    end

    def create
     # render plain: params[:article].inspect
     @article=Article.new(article_params)
     if @article.save
       flash[:notice]="Article was successfully created"
       redirect_to article_path(@article)
     else
       render 'new' # or :new
     end
    end
    
    def show
      
    end
    
   #  Route for editing articles takes the form ->
   #  /articles/:id/edit

    def edit 

    end

    def update
     

      if @article.update(article_params)
         flash[:notice]="Articl was successfully updated"
         redirect_to article_path(@article)
      else
          render 'edit'
      end
    end
    
    def destroy
    
      @article.destroy
      flash[:notice]="Article was deleted"
      redirect_to articles_path
    end

    private
     def set_article
      @article =Article.find(params[:id])
     end
     def article_params
        params.require(:article).permit(:title, :description)
     end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home #action==>method
   
    end
   
    def about #action==>method
   
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<!--#this is a partial > to avoid redundancy-->
<% if @article.errors.any? %>
    <h2>The following errors prevented the article from getting created</h2>
    <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
<% end %>

<%= form_for @article do |f| %>
    <p>
        <%= f.label :title %><br/>
        <%= f.text_field :title %>
    </p>
    <p>
        <%= f.label :description %><br/>
        <%= f.text_area :description %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>

<%= link_to "Back to articles listing", articles_path%>

app/views/articles/edit.html.erb
<h1>Edit existing article</h1>

<%= render 'form'%>
<!--
#for shared directory# 'shared/form'---->

app/views/articles/index.html.erb
<h1> Listing all articles </h1>
<p>
 <%= link_to "Create new article", new_article_path%>
</p>
<table>
 <tr>
   <th>Title</th>
   <th>Description</th> 
 </tr>

 <% @articles.each do |article|%>
    <tr>
        <td><%= article.title%></td>
        <td><%= article.description%></td>
        <td><%= link_to "Edit", edit_article_path(article)%></td>
        <td><%= link_to "Show", article_path(article)%></td>
        <td><%= link_to "Delete", article_path(article), method: :delete, data: {confirm: "Are you sure?"}%></td>
    </tr>
 <%end%>
</table>

app/views/articles/new.html.erb
<h1> Create an article</h1>

<%= render 'form'%>
 <!-- form helpers

# <% if @article.errors.any?%>
# <h2> Following are errors </h2>
# <ul>
#    <% @article.errors.full_messages.each do |msg| %>
#       <li><%= msg%></li> 
#    <%end%>
# </ul>
# <% end %>

# <%= form_for @article do |f| %>
#  <p>
#     <%= f.label :title %><br>
#     <%= f.text_field :title %>
#  </p>
#  <p>
#     <%= f.label :description %><br>
#     <%= f.text_field :description %>
#  </p>
#  <p>
#     <%= f.submit%>
#  </p>

# <% end %>

# <%= link_to "Back to articles listing", articles_path%>
-->

app/views/articles/show.html.erb
<h1> Showing selected article </h1>

<p>
  Title: <%= @article.title%>
</p>

<p>
  Description: <%= @article.description%>
</p>

<%= link_to "Edit this article", edit_article_path(@article)%> |
<%= link_to "Back to articles listing", articles_path%>

app/views/layouts/_messages.html.erb
<% flash.each do |name,msg|%>
    <ul>
     <li> <%= msg%> </li>
    </ul>  
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Alpha blog", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        
        <a class="nav-link" href="#">Articles <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


  </head>

  <body>
    <%=render 'layouts/navigation'%>
    <%=render 'layouts/messages'%> <!--#becoz default path for render is articles folder-->
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb

<h1>THIS IS ABOUT PAGE</h1>

<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<h1>THIS IS HOME PAGE OF BLOG APP</h1>

<%= link_to "Alpha Blog", articles_path%> | <%=link_to 'About', about_path %>

<!--this is emmbedded ruby-->
<%= %>